# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='org_rank',
            field=models.PositiveIntegerField(default=0, help_text='Staff members who are more important (eg General Manager should recieve lower values, while those in lower positions (eg Office Assistant) should recieve a higher value here.', verbose_name='Orginizational Weight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='bio',
            field=models.TextField(),
        ),
    ]
